# .github/workflows/snake.yml
name: Generate Snake

on:
  schedule: [{ cron: "0 0 * * *" }]   # 매일 UTC 00:00
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: lumo-chat-11
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
